### PR TITLE
use local jquery based lib to generage QR code instead of Google Charts

### PR DESCRIPTION
**Pull request by Ths2-9Y-LqJt6**
Hey @julien731, I love your plugin! I was thinking that it'd be a bit more secure and less fragile (and more classy?) to not be dependent on any 3rd parties to make the plugin work.  To that end, here's a pull request that replaces Google's Chart API with a [jQuery based one](https://larsjung.de/jquery-qrcode/). 

Lemme know what ya think!

### CODE REVIEW

**Comment by julien731** [comment]
Many thanks for the PR. I'll totally merge it into core. There is just one small thing though. I have been testing your code. It all looks fine, except that now the modal window has a vertical scrollbar when showing the QR code.

image

Are you also seeing this or is it just me?

**Comment by Ths2-9Y-LqJt6** [comment]
Cool, I'm glad you're open to my PR! I was seeing some extra scroll bars when I was testing myself, but thought I had fixed them in my final commit.  I'll take another look and get back to ya!

BTW - What browser/OS are you seeing this in?

**Comment by Ths2-9Y-LqJt6** [comment]
Okie dokie! I spotted the vertical scrolling straight away - thanks for the QA on that. Easy fix was to do inline css of `padding:0;margin:0;` on the `<p/>` tag in the tickbox. Check commit 754f303 for the fix.

As well, I saw you made some upstream changes, so please check that I did that merge correctly in 669331c.

**Comment by Ths2-9Y-LqJt6** [comment]
@julien731  - Any updates on this PR?  I'd love to help!

**Comment by Ths2-9Y-LqJt6** [comment]
@julien731  - awesome, thanks!

**Pull request merged**
